"""empty message

Revision ID: 1867a34b21e4
Revises: 9e93957fc69d
Create Date: 2016-03-30 10:20:21.091417

"""

# revision identifiers, used by Alembic.
revision = '1867a34b21e4'
down_revision = '9e93957fc69d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asserts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asserts_name'), 'asserts', ['name'], unique=True)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assert_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('serial_code', sa.String(length=255), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('assert_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('date_assigned', sa.DateTime(), nullable=True),
    sa.Column('date_returned', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assert_id'], ['asserts.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_date_assigned'), 'assignments', ['date_assigned'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_date_assigned'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_asserts_name'), table_name='asserts')
    op.drop_table('asserts')
    ### end Alembic commands ###
