"""empty message

Revision ID: 23e73745e4e6
Revises: 93411e789118
Create Date: 2016-03-31 02:59:10.752882

"""

# revision identifiers, used by Alembic.
revision = '23e73745e4e6'
down_revision = '93411e789118'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('assigned', sa.Boolean(), nullable=True))
    op.add_column('inventories', sa.Column('revolved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'revolved')
    op.drop_column('inventories', 'assigned')
    ### end Alembic commands ###
